import React, { useState, useEffect } from "react";

export default function Interview() {


	return (
		<div className='interview_info' >

        <ul className='interview-advice-list' >
          <li className='interview-advice-header'>Virtual Interview Tips</li>
          <li className='interview-advice'>Make sure you are centered in the video screen</li>
          <li className='interview-advice-sub'>We need to make sure you are the focus of the interview. If you are too low in the frame it looks like they are talking to the top of your head and that you may be hiding something. Too high in the frame and it will look like you are looking down at them. You want to be as close to dead center as possible to really push your ability to make that connection with the interviewer.</li>
          <li className='interview-advice'>Prepare how you would for an in person interview</li>
          <li className='interview-advice-sub'>If the interviewer is treating it like a real interview so should you! This is going to a be a real job that will pay you real money. The interviewer will be taking real time out of their real workday. You need to treat it with the same respect and consideration you would an in person interview because at the end of the day there are real stakes and real rewards for doing well.</li>
          <li className='interview-advice'>Make sure your computer is working and has a stable internet connection</li>
          <li className='interview-advice-sub'>You do not want to ruin a great interview with a with a disconnection... Both you and the interviewer are taking time out of the day to meet each other to see if you are right for their company, neither of you want to have that time or chance wasted by technical issues. Test out zoom or whatever service you are planning to meet on the night before the interview. Make sure you either have a direct network connection via ethernet, or at least make sure you are in a part of your house where the wifi is best. You do not want to have issues understanding each other and making that connection because of lag. I would recommend to test out the video platform beforehand make sure you a familiar with the tools available such a screen share, virtual background and any other tools that may be useful to the interview. </li>
          <li className='interview-advice'>Be mindful of your surroundings</li>
          <li className='interview-advice-sub'>Think of what else is visible in the video, Do you have garbage stacked on your desk? Do you have things hanging on the wall behind you that might not present your best self? Virtual backgrounds on some video conferencing services such as zoom can be a helpful tool if you do not have a good presenting place available. If you do choose to use this tool, make sure that you choose a professional background that will help convey you in a good light. If you have a particular color you feel really helps present you well as a background it may be worth getting an image with a gradient of that color for your background may help make you feel more confident and come across better.</li>
          <li className='interview-advice'>Think about audio</li>
          <li className='interview-advice-sub'>Make sure to annunciate, if your audio quality is not the best, you may be misunderstood if you are not speaking loudly and clearly. Try to give yourself A quiet space, if at all possible be in another room thn family or friends. You want limit the possibility of the interviewer hearing anything that is not you. It can be distracting for both of you if all of the sudden you hear little bobby yelling that his Xbox won't turn on. While it may not always be possible to control your environment it, it is important to do your best to so that you come across as someone who is professional and in control of their professional environment</li>
          <li className='interview-advice'>Dress as formal as you would for an in person interview</li>
          <li className='interview-advice-sub'>You want to put forward a professional appearance. Always dress a level above the job you are going for. If you are going for job where you would be wearing t-shirt and jeans, wear business casual. If it's business casual than dress with business attire. The whole point is to have your interviewer view you as their peer and show off your professional presence. </li>
          <li className='interview-advice'>Lighting</li>
          <li className='interview-advice-sub'>Make sure you are well lit, you want it as well lose to looking like a real interview as possible and most of us do not interview with the lights off. Check for glare eye contact means a lot even online. If your glasses (if you have glasses) have to much glare and they cannot see your eyes, it is harder to make a connection. If possible you want to have front lighting. You want to try to get yourself to look as close to possible to looking like a natural lighting as if you were there with them in person. Test your lighting beforehand open up your webcam and see you how you look. You can pick up cheap lighting tools from walmart for under $20 to improve how you come across.  </li>
          <li className='interview-advice'>Nonverbal communication</li>
          <li className='interview-advice-sub'>You want to take advantage this as much as possible since you are not there in person to do so. Make sure to pay attention to posture and eye contact as well as your facial expressions to show engagement. Start with a virtual handshake, a wave, a smile and a nod. Since you are not there to shake their hand it is important to start that connection off right. Make sure to be emotive, people tend to connect with people more when they feel they can tell their emotions and intent. If the interviewer can read that you are happy when you say you are happy to meet them. The opposite can be a real issue, if you say your happy to be there but you look angry or sad tht disjoint in body language can really turn and interviewer off to the idea of working with you. </li>
          <li className='interview-advice'>Let the interviewer finish speaking.</li>
          <li className='interview-advice-sub'>People may be more likely to miss cues as to weather or not the other person is done speaking over video, when you think they are done speaking give them a couple seconds more to make sure they are don and it gives you a little more time to prepare your answer. In general being polite is going to take you far. You want to take the time to show them that you are polite and respectful and that they could see themselves working with you, People want to work with polite coworkers.</li>
          <li className='interview-advice'>Make it obvious when you are done speaking</li>
          <li className='interview-advice-sub'>On the other side they may have trouble knowing when you are done, try to either nod to give them ask them a question to indicate that you are done. You want to avoid dead air. If it is not to clear that you are done that can lead to awkward silences. Awkward situations tend to put people into a nervous state. Being in a nervous state tends to make people not present their best most confident self.</li>
          <li className='interview-advice'>Do research on the company you are interviewing for</li>
          <li className='interview-advice-sub'>Do your homework, you are interviewing them as much as they are interviewing you, ask good questions about the company and be able tell them specific reason why you want to work at their company. You can get good information from their job posting. I would also take a look at the companies website, learn what they do, what their mission is and how you can fit into their company. Learn what they are trying to accomplish and try to relate your experience back to that goal, Let them know how you are going to hit the ground running working towards their companies goals.  </li>
          <li className='interview-advice'>Be a bit early</li>
          <li className='interview-advice-sub'>Whether it is in person or virtual it is still very important to be at least 5 minutes early to the interview, most interviewers will dismiss the possibility of hiring you if you show up late. This goes back to the importance of both yours and the interviewers time. Being late is often considered a sign of disrespect as well as if you cannot be on time for the first meeting which is what they consider to be their first impression of you what are the hopes of you showing up on time for the job. There are of course roadblocks that come up for us all but just make sure to be professional and inform them as quickly as possible. </li>
          <li className='interview-advice'>Connect</li>
          <li className='interview-advice-sub'>Really try to show them your personality, they need to be able to see themselves working with you. Try to come across as someone you would want to work with too, while they need to know you have the specific job skills, they are also interviewing you to see if you would be a good cultural fit with their team. Good luck have fun and get that job!</li>
        </ul>

          <img className="interview-guide" src='/interviewGuide.png' />
		</div>
	);
}
